id: P000756
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:01:20.858225
source_metadata:
  id: bdr:W1KG22374
  title: མ་འོངས་ལུང་བསྟན་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  volumes:
    423343ea76f248bc97e62b93a0285d4a:
      image_group_id: I1KG22387
      title: ''
      volume_number: 1
      total_pages: 546
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
