id: P000756
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22374
  title: མ་འོངས་ལུང་བསྟན་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  volumes:
    423343ea76f248bc97e62b93a0285d4a:
      image_group_id: I1KG22387
      title: ''
      volume_number: 1
      total_pages: 546
